### ISSUE TITLE
Checkpoints release

### ISSUE THREAD

**Issue by sirfoga** [XGGNet/Domain-generalization-with-task-augmentation-for-MIA#2]
Thanks for your paper "Domain Generalization on Medical Imaging Classification using Episodic Training with Task Augmentation": I found it very interesting and motivating! We were thinking of using it for our current task: abdominal organ segmentation in the wild. Can you provide us the checkpoints (model weights) of your trained models (on the 4 mentioned experiments of Table 4)?

**Comment by chenxinli001** [comment]
Thank you for your interests. I think in-the-wild setting is practical&interesting for abdominal organ segmentation. For checkpoints, I haven't uploaded them online. Since I have graduated, I will try out to get my co-authors in the lab to find out whether some of them are still in the servers (it may take some time). Once done, I will update this repository.
